stages:
- build
- deploy

image: node:10.12-alpine

build:
  stage: build
  artifacts:
    paths:
    - build
  script:
  - npm install
  - npm run build

deploy:
  stage: deploy
  only:
  - master
  environment:
    name: production
    url: $PRODUCTION_URL
  before_script:
  - npm install -g firebase-tools
  script:
  - firebase deploy --only hosting --token $TOKEN
