stages:
- build
- deploy

build:
  stage: build
  image: node:10.12-alpine
  artifacts:
    paths:
    - build
  script:
  - npm install
  - npm run build

deploy:
  image: node:10.12-alpine
  stage: deploy
  only:
  - master
  environment:
    name: production
    url: $PRODUCTION_URL
  before_script:
  - npm install -g firebase-tools
  script:
  - firebase deploy --only hosting --token $TOKEN
